// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdXuW6N0sjBVyMYPyq4vt_9ZTdg5rzusA',
    appId: '1:70051656301:web:3e0b6e39103958945d8564',
    messagingSenderId: '70051656301',
    projectId: 'upipets-ffc92',
    authDomain: 'upipets-ffc92.firebaseapp.com',
    databaseURL: 'https://upipets-ffc92-default-rtdb.firebaseio.com',
    storageBucket: 'upipets-ffc92.firebasestorage.app',
    measurementId: 'G-PGTXRDRF56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5rMr0MBXsR0Sk-Djy9eajuoD9OHeta6w',
    appId: '1:70051656301:android:980e2c6c66a478635d8564',
    messagingSenderId: '70051656301',
    projectId: 'upipets-ffc92',
    databaseURL: 'https://upipets-ffc92-default-rtdb.firebaseio.com',
    storageBucket: 'upipets-ffc92.firebasestorage.app',
  );
}
