// Mocks generated by Mockito 5.4.6 from annotations
// in proyecto_tutorias/test/features/login/viewmodels/login_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i7;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:proyecto_tutorias/data/models/user_model.dart' as _i5;
import 'package:proyecto_tutorias/data/repositories/auth_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i4.User?>.empty(),
          )
          as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<_i4.User?> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.UserModel?> checkStudentStatus(String? boleta) =>
      (super.noSuchMethod(
            Invocation.method(#checkStudentStatus, [boleta]),
            returnValue: _i3.Future<_i5.UserModel?>.value(),
          )
          as _i3.Future<_i5.UserModel?>);

  @override
  _i3.Future<void> activateAccount({
    required String? docId,
    required String? email,
    required String? password,
    required String? phone,
    required String? personalEmail,
    required String? dictamenFileName,
    _i6.File? dictamenFileMobile,
    _i7.Uint8List? dictamenFileWeb,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#activateAccount, [], {
              #docId: docId,
              #email: email,
              #password: password,
              #phone: phone,
              #personalEmail: personalEmail,
              #dictamenFileName: dictamenFileName,
              #dictamenFileMobile: dictamenFileMobile,
              #dictamenFileWeb: dictamenFileWeb,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.UserModel?> getCurrentUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserData, []),
            returnValue: _i3.Future<_i5.UserModel?>.value(),
          )
          as _i3.Future<_i5.UserModel?>);

  @override
  _i3.Future<void> uploadEvidence({
    required String? materia,
    required String? mes,
    required String? fileName,
    _i6.File? fileMobile,
    _i7.Uint8List? fileWeb,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadEvidence, [], {
              #materia: materia,
              #mes: mes,
              #fileName: fileName,
              #fileMobile: fileMobile,
              #fileWeb: fileWeb,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reviewEvidence({
    required String? evidenceId,
    required String? newStatus,
    String? feedback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reviewEvidence, [], {
              #evidenceId: evidenceId,
              #newStatus: newStatus,
              #feedback: feedback,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> assignFinalGrade({
    required String? studentId,
    required double? finalGrade,
    required String? finalStatus,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#assignFinalGrade, [], {
              #studentId: studentId,
              #finalGrade: finalGrade,
              #finalStatus: finalStatus,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
